/* 
 * Interface representing a model object.
 */
export interface ModelObject {
    ownerSlug: string|undefined;
    model: {slug: string;
        title: string;
        id: number;
        isPrivate: boolean;
        versionId: number;
        voters: [];
        licenseGroups: [];
        instances: [];
        frameworks: [];
        autoGeneratedSources: [];
        authors: [];
        moderationStatus: string;
        links: string[];
        implementationModels: []},
    
}

/*
 * Class for managing model information.
 */
export class Model {
    ownerSlug: string|undefined;
    model: object;
    slug: string;
    title: string;
    id: number;
    isPrivate: boolean;
    versionId: number;
    voters: [];
    licenseGroups: [];
    instances: [];
    frameworks: [];
    autoGeneratedSources: [];
    authors: [];
    moderationStatus: string;
    links: [string];
    implementationModels: []

    /** 
     * Static method to create an instance of Model.
     *
     * @returns An instance of Model.
     */
    public static builder(): Model {
        return new Model();
    }

    /**
     * Builds and returns the ModelObject.
     *
     * @returns The ModelObject.
     */
    public build(): ModelObject{
        return {
            ownerSlug: this.ownerSlug,
            model:{
            slug: this.slug,
            title: this.title,
            id: 0,
            isPrivate: this.isPrivate,
            versionId: 0,
            voters: [],
            licenseGroups: [],
            instances: [],
            frameworks: [],
            autoGeneratedSources: [],
            authors: [],
            moderationStatus: "PRIVATED_MODERATION_STATUS_NO_ABUSE",
            links: [],
            implementationModels: []
            }
        };
    }

    /** 
     * Sets the patientId for the PatientNote.
     *
     * @param patientId - The patientId to set.
     * @returns The Model instance for method chaining.
     */
    public setOwnerSlug(): this {
        this.ownerSlug = process.env.OWNER;
        return this;
    }

    /** 
     * Sets the slug for the Model.
     *
     * @param slug - The slug to set.
     * @returns The Model instance for method chaining.
     */
    public setSlug(): this {
        this.slug = this.title+'-slug';
        return this;
    }

    /** 
     * Sets the title for the Model.
     *
     * @param title - The slug to set.
     * @returns The Model instance for method chaining.
     */
    public setTitle(title: string): this {
        this.title = title;
        return this;
    }

    /** 
     * Sets the isPrivate for the Model.
     *
     * @param isPrivate - The slug to set.
     * @returns The Model instance for method chaining.
     */
    public setIsPrivate(isPrivate: string): this {
        this.isPrivate = isPrivate==='Private'?true:false;
        return this;
    }
}