name: Configurable Job Test Run(2)

on:
  workflow_dispatch:
    inputs:
      operatingSystem:
        type: string
        required: true
        description: Type system on which you want to run
      environment-name:
        description: Choose an environment
        required: true
        default: ENV1
        type: choice
        options:
          - ENV1
          - ENV2

jobs:
  run_tests:
    name: Run smoke tests on ${{ github.event.inputs.environment-name }}
    if: ${{ github.event.inputs.environment-name == 'ENV1' }}
    with:
      os-system: ubuntu-latest
      environment-name: ENV1
      suite-name: Dataset
      timeout-before-force-stop: 120
      branch-name: master
    secrets: inherit

    if: ${{ github.event.inputs.environment-name == 'ENV2' }}
    with:
      os-system: ubuntu-latest
      environment-name: ENV2
      suite-name: Model
      timeout-before-force-stop: 150
      branch-name: master
    secrets: inherit     