name: Configurable Job Test Run

on:
  workflow_dispatch:
    inputs:
      operatingSystem:
        type: string
        required: true
        description: Type system on which you want to run
      environment-name:
        description: Choose an environment
        required: true
        default: ENV1
        type: choice
        options:
          - ENV1
          - ENV2

jobs:
  run_tests:
    name: Run smoke tests
    runs-on: ${{ github.event.inputs.operatingSystem }}
    environment: ${{ github.event.inputs.environment-name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch-name }}

      - name: Setup node
        uses: actions/setup-node@v3
        
      - name: Install dependencies
        run: npm ci

      - name: Install playwright browsers
        run: npx playwright install --with-deps

      - name: Run tests on ${{ github.event.inputs.environment-name }}
        if: ${{ github.event.inputs.environment-name == 'ENV1' }}
        run: npx playwright test -g "@smokeDataset"
        env:
          SITE_URL: ${{ vars.SITE_URL }}
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          CREATE_DATASET_ENDPOINT: ${{ secrets.CREATE_DATASET_ENDPOINT }}
          DELETE_DATASET_ENDPOINT: ${{ secrets.DELETE_DATASET_ENDPOINT }}
          CREATE_MODEL_ENDPOINT: ${{ secrets.CREATE_MODEL_ENDPOINT }}
          DELETE_MODEL_ENDPOINT: ${{ secrets.DELETE_MODEL_ENDPOINT }}  
          CREATE_COLLECTION_ENDPOINT: ${{ secrets.CREATE_COLLECTION_ENDPOINT }}
          DELETE_COLLECTION_ENDPOINT: ${{ secrets.DELETE_COLLECTION_ENDPOINT }}
          LIST_COLLECTIONS_ENDPOINT: ${{ secrets.LIST_COLLECTIONS_ENDPOINT }}

      - name: Run tests on ${{ github.event.inputs.environment-name }}
        if: ${{ github.event.inputs.environment-name == 'ENV2' }}
        run: npx playwright test -g "@smokeModel"
        env:
          SITE_URL: ${{ vars.SITE_URL }}
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          CREATE_DATASET_ENDPOINT: ${{ secrets.CREATE_DATASET_ENDPOINT }}
          DELETE_DATASET_ENDPOINT: ${{ secrets.DELETE_DATASET_ENDPOINT }}
          CREATE_MODEL_ENDPOINT: ${{ secrets.CREATE_MODEL_ENDPOINT }}
          DELETE_MODEL_ENDPOINT: ${{ secrets.DELETE_MODEL_ENDPOINT }}   
          CREATE_COLLECTION_ENDPOINT: ${{ secrets.CREATE_COLLECTION_ENDPOINT }}
          DELETE_COLLECTION_ENDPOINT: ${{ secrets.DELETE_COLLECTION_ENDPOINT }}
          LIST_COLLECTIONS_ENDPOINT: ${{ secrets.LIST_COLLECTIONS_ENDPOINT }}     