name: Smoke Tests Run - General
run-name: Smoke Test Run

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  DATASETS:
    name: Dataset tests
    uses: ./.github/workflows/template.yml
    with:
      os-system: ubuntu-latest
      environment-name: ENV1
      suite-name: Dataset
      timeout-before-force-stop: 120
      branch-name: master
    secrets: inherit

  MODELS:
    name: Model tests
    needs: DATASETS
    uses: ./.github/workflows/template.yml
    with:
      os-system: ubuntu-latest
      environment-name: ENV2
      suite-name: Model
      timeout-before-force-stop: 150
      branch-name: master
    secrets: inherit
  
  MAIL:
    name: Send mail
    if: failure()
    uses: https://github.com/dawidd6/action-send-mail@v3
    with:
        to: ${{ secrets.MAIL_TO }}
        from: Gitea <gitea@hostname>
        subject: Automatic Message on Job Failure
        priority: high
        convert_markdown: true
        html_body: |
            ### Some job in this workflow has failed