name: Smoke Tests Run - General
run-name: Smoke Test Run

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  DATASETS:
    name: Dataset tests
    uses: ./.github/workflows/template.yml
    with:
      os-system: ubuntu-latest
      environment-name: ENV1
      suite-name: Dataset
      timeout-before-force-stop: 120
      branch-name: master
    secrets: inherit

  MODELS:
    name: Model tests
    needs: DATASETS
    uses: ./.github/workflows/template.yml
    with:
      os-system: ubuntu-latest
      environment-name: ENV2
      suite-name: Model
      timeout-before-force-stop: 150
      branch-name: master
    secrets: inherit