on:
  workflow_call:
    inputs:
      os-system:
        required: false
        type: string
        default: ubuntu-latest
      suite-name:
        required: true
        type: string
      environment-name:
        required: true
        type: string
      branch-name:
        required: false
        type: string
        default: master
      timeout-before-force-stop:
        required: false
        type: number
        default: 180

jobs:
  run:
    name: ${{ inputs.environment-name }}
    runs-on: ${{ inputs.os-system }}
    environment: ${{ inputs.environment-name }}
    timeout-minutes: ${{ inputs.timeout-before-force-stop }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch-name }}

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
        
      - name: Install dependencies
        run: npm ci

      - name: Install playwright browsers
        run: npx playwright install --with-deps

      - name: Record Start Time
        id: record_start
        run: echo "start_time=$(date +%s)" >> $GITHUB_ENV

      - name: Run_tests
        run: npx playwright test -g "@smoke${{ inputs.suite-name }}"
        env:
          SITE_URL: ${{ vars.SITE_URL }}
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          CREATE_DATASET_ENDPOINT: ${{ secrets.CREATE_DATASET_ENDPOINT }}
          DELETE_DATASET_ENDPOINT: ${{ secrets.DELETE_DATASET_ENDPOINT }}
          CREATE_MODEL_ENDPOINT: ${{ secrets.CREATE_MODEL_ENDPOINT }}
          DELETE_MODEL_ENDPOINT: ${{ secrets.DELETE_MODEL_ENDPOINT }}
          CREATE_COLLECTION_ENDPOINT: ${{ secrets.CREATE_COLLECTION_ENDPOINT }}
          DELETE_COLLECTION_ENDPOINT: ${{ secrets.DELETE_COLLECTION_ENDPOINT }}
          LIST_COLLECTIONS_ENDPOINT: ${{ secrets.LIST_COLLECTIONS_ENDPOINT }}
          MAIL_TO: ${{ secrets.MAIL_TO }}

      - name: Calculate Execution Time
        id: calc_time
        run: |
          end_time=$(date +%s)
          total_time=$((end_time - $start_time))
          echo "Execution Time: $total_time seconds"
          echo "total_time=$total_time" >> $GITHUB_ENV

      - name: Collect artifacts
        if: env.total_time > 45
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/
          retention-days: 2

      - name: Send mail
        if: steps.Run_tests.outcome == 'failure'
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.ukr.net
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          to: ${{ secrets.MAIL_TO }}
          from: ${{ secrets.MAIL_SENDER_NAME }} <${{ secrets.MAIL_FROM }}>
          subject: Automatic Message on Job Failure
          priority: high
          convert_markdown: true
          html_body: |
            <h1> ${{ inputs.suite-name }} tests job in ${{ github.workflow }} has failed </h1>
      

      